# Generated by Django 3.1.6 on 2021-03-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210327_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_register',
            old_name='user',
            new_name='student',
        ),
    ]
