# Generated by Django 3.1.6 on 2021-03-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210330_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_preference', models.CharField(choices=[('Morning batch (7:30 to 11:00)', 'Morning batch (7:30 to 11:00)'), ('Afternoon batch (1:30 to 4:00)', 'Afternoon batch (1:30 to 4:00)'), ('Evening batch (5:30 to 8:00)', 'Evening batch (5:30 to 8:00)')], default=None, max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile/profile.jpg', null=True, upload_to='profile/'),
        ),
        migrations.DeleteModel(
            name='Course_register',
        ),
        migrations.AddField(
            model_name='course_enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student'),
        ),
    ]
