# Generated by Django 3.1.6 on 2021-04-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_allocated',
            field=models.CharField(choices=[('7:30 a.m', '7:30 a.m'), ('8:00 a.m', '8:00 a.m'), ('8:30 a.m', '8:30 a.m'), ('9:00 a.m', '9:00 a.m'), ('9:30 a.m', '9:30 a.m'), ('10:00 a.m', '10:00 a.m'), ('10:30 a.m', '10:30 a.m'), ('11:00 a.m', '11:00 a.m'), ('1:30 p.m', '1:30 p.m'), ('2:00 p.m', '2:00 p.m'), ('2:30 p.m', '2:30 p.m'), ('3:00 p.m', '3:00 p.m'), ('3:30 p.m', '3:30 p.m'), ('4:00 p.m', '4:00 p.m'), ('5:30 p.m', '5:30 p.m'), ('6:00 p.m', '6:00 p.m'), ('6:30 p.m', '6:30 p.m'), ('7:30 p.m', '7:30 p.m'), ('8:00 p.m', '8:00 p.m')], default=None, max_length=30),
        ),
    ]
