# Generated by Django 3.1.6 on 2021-04-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Not started', 'Not started')], default='Not started', max_length=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.schedule')),
            ],
        ),
    ]
