# Generated by Django 3.1.6 on 2021-04-16 09:35

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_book_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_enrollment',
            name='course',
            field=models.ForeignKey(help_text='Enroll in another course after completion of your first course', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, help_text='the date format is: year-month-date', null=True, validators=[courses.models.validate_age]),
        ),
    ]
